export interface Order {
    id: string
    channel: string
    channel_id: any
    notes: any
    customerName: string
    channel_name: string
    fulfillment_status: any
    financial_status: any
    active: any
    store: any
    items: any
    storeCreatedAt: any
    storeClosedAt: any
    customerEmail: string
    customerPhone: string
    customerCountry: string
    customerProvince: string
    customerCountryCode: string
    customerProvinceCode: string
    customerCity: any
    customerZip: any
    customerSelectedShipping: any
    shipperCountry: string
    shipperProvince: string
    shipperCountryCode: string
    shipperProvinceCode: string
    riskLevel: any
    riskMessage: any
    cancelled: any
    cancelReason: any
    cancelledAt: any
    price: any
    currency: any
    fulfillment: any
    latitude: any
    longitude: any
    trackingEnabled: boolean
    createdAt: string
    updatedAt: string
    orgId: string
    createdById: string
  }